# Generated by Django 4.2 on 2023-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_forms', '0003_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Session2',
        ),
        migrations.RenameField(
            model_name='session2',
            old_name='session_id',
            new_name='session2_id',
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='info',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
