# Generated by Django 4.2 on 2023-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_model', '0004_alter_product_categories_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaa', models.CharField(max_length=250)),
            ],
        ),
    ]
